In [1]:
import numpy as np
from keras.models import Sequential #Así se llama la librería
from keras.layers import Dense # Así se llama la capa

In [2]:
# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[0,0 ],[0,1 ],[1,0],[1,1]])

# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[[0 ],[ 0],[ 0]],[[ 1],[0],[1]],[[0],[1],[1]],[[1],[1],[1]]])

In [3]:
print(target_data)

[[[0]
  [0]
  [0]]

 [[1]
  [0]
  [1]]

 [[0]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]


In [4]:
print(training_data)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


# Definimos una arquitectura de red neuronal

In [5]:
model = Sequential() #Aquí le asignamos un nombre o variable al modelo Sequential
model.add(Dense(200, input_dim=2, activation='relu')) #add es agrega y dice, agrega una capa densa, el 16 es el número de neuronas, input dim son las dimensiones para este caso son dos, la función de activación ("relu") es como el airling, se le conoce como la función de rectificación
model.add(Dense(3, activation='sigmoid')) #en el primer parámetro le ponemos 1 porque basta una neurona para que nos dé un cero y un 1 y de función de activación se usa la sigmoide

In [6]:
#Ahora le vamos a dar los datos de entrenamiento
model.compile(loss='mean_squared_error', #Aquí le ponemos la función para evaluar el error, usaremos la función de costo o de error cuadrático medio
              optimizer='adam', #En optimizador le ponemos adam, mañana lo explica
              metrics=['binary_accuracy'])

# Entrenamiento de la red

In [7]:
model.fit(training_data,target_data , epochs=1000) #Aquí le ponemos lo que queremos meter y en el segundo parámetro a donde queremos llegar

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 0.2575 - binary_accuracy: 0.5833
Epoch 2/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.2545 - binary_accuracy: 0.3333
Epoch 3/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.2516 - binary_accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.2487 - binary_accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.2459 - binary_accuracy: 0.5833
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.2431 - binary_accuracy: 0.6667
Epoch 7/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.2403 - binary_accuracy: 0.6667
Epoch 8/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.2377 - binary_accuracy: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.2351 - binary_accuracy: 0.8333
Epoch 10/1000
1/1 [=============================

In [8]:
# evaluamos el modelo
scores = model.evaluate(training_data, target_data) #Aquí le preguntamos qué tan bien evalúa, le pasamos para evaluar el target data

1/1 [==============================] - 0s 157ms/step - loss: 4.0343e-04 - binary_accuracy: 1.0000


In [10]:

print (model.predict(training_data).round()) #Si le quitamos el round nos da las verdaderas salidas, ya que, redondeoa

1/1 [==============================] - 0s 42ms/step
[[0.02234344 0.02099605 0.03587546]
 [0.9831235  0.01850848 0.9782431 ]
 [0.021361   0.98451823 0.9779467 ]
 [0.98654914 0.987751   0.9999744 ]]
